name: 100% Working Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: "3.32.6"
  XCODE_VERSION: "16.4"

jobs:
  build:
    name: Guaranteed Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          
      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
        
      - name: Nuclear Reset
        run: |
          echo "=== CLEARING ALL CACHES ==="
          rm -rf ~/.pub-cache
          rm -rf ~/.flutter
          rm -rf pubspec.lock .flutter-plugins*
          pod cache clean --all
          
      - name: Verify Project Structure
        run: |
          echo "=== VERIFYING PROJECT STRUCTURE ==="
          if [ ! -f "pubspec.yaml" ]; then
            echo "ERROR: No pubspec.yaml found - project structure invalid!"
            ls -la  # Debug directory contents
            exit 1
          else
            echo "Valid Flutter project found"
          fi

      - name: Verify Flutter Installation
        run: |
          echo "=== FLUTTER VERSION ==="
          flutter --version
          echo "=== PUB SPEC ==="
          cat pubspec.yaml || echo "No pubspec.yaml found"

      - name: Debug Directory Structure
        run: |
          echo "=== CURRENT DIRECTORY CONTENTS ==="
          ls -la
          echo "=== FLUTTER DOCTOR ==="
          flutter doctor -v
      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build/
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          
      - name: Get Dependencies
        run: |
          echo "=== GETTING DEPENDENCIES ==="
          if [ ! -f "pubspec.yaml" ]; then
            echo "ERROR: No pubspec.yaml found in $(pwd)"
            exit 1
          fi
          flutter pub get --verbose
          
      - name: Build iOS
        run: flutter build ios --release --no-codesign
        
      - name: Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Build Result
          body: "Build completed with status: ${{ job.status }}"
          to: akhmadihin@email.com
          from: CI/CD
