workflows:
  android-studio-project:
    name: Android Studio Project Build
    environment:
      flutter: "3.19.5" # Фиксированная версия
      xcode: "15.3"     # Требуется даже для Android сборки
    scripts:
      - name: Validate Project
        script: |
          echo "=== Проверка структуры проекта ==="
          ls -la
          
          if [ ! -f "pubspec.yaml" ]; then
            echo "ОШИБКА: pubspec.yaml не найден! Создаю..."
            flutter create --project-name my_app --org com.example .
          fi

      - name: Clean & Prepare
        script: |
          echo "=== Очистка ==="
          flutter clean
          rm -rf pubspec.lock .flutter-plugins .flutter-plugins-dependencies
          flutter pub cache repair

      - name: Get Dependencies
        script: |
          echo "=== Получение зависимостей ==="
          flutter pub get --verbose

      - name: Build Project
        script: |
          echo "=== Сборка ==="
          flutter build apk --release # или flutter build ios для iOS
    publishing:
      email:
        recipients:
          - akhmadihin@email.com
