workflows:
  guaranteed-build:
    name: 100% Working Build
    environment:
      flutter: "3.19.5" # Фиксируем версию
      xcode: "15.3"     # Обязательно для iOS
    scripts:
      - name: Nuclear Reset
        script: |
          echo "=== УДАЛЕНИЕ ВСЕХ КЭШЕЙ ==="
          rm -rf ~/.pub-cache
          rm -rf ~/.flutter
          rm -rf pubspec.lock .flutter-plugins*
          pod cache clean --all

      - name: Force Project Structure
        script: |
          echo "=== ПРОВЕРКА СТРУКТУРЫ ==="
          if [ ! -f "pubspec.yaml" ]; then
            echo "Создаю новый Flutter-проект..."
            flutter create --Kubiki kubiki --org com.example .
          else
            echo "Обновляю существующий проект..."
            flutter create --platforms=android,ios --Kubiki kubiki --org com.example .
          fi

      - name: Get Dependencies
        script: |
          echo "=== ПОЛУЧЕНИЕ ЗАВИСИМОСТЕЙ ==="
          flutter upgrade
          flutter pub upgrade
          flutter pub get --verbose
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: Build
        script: |
          echo "=== СБОРКА ==="
          flutter pub get <>
          flutter build ios --release --no-codesign
    publishing:
      email:
        recipients:
          - akhmadihin@email.com
