workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "stable"
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    publishing:
      email:
        recipients:
          - your@email.com
