workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "stable"
      xcode: "15.2"
    scripts:
      - name: Validate Project
        script: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "Creating default pubspec.yaml..."
            cat <<EOF > pubspec.yaml
            name: my_app
            description: A new Flutter project
            version: 1.0.0+1
            
            environment:
              sdk: ">=3.0.0 <4.0.0"
              flutter: ">=3.16.0"
            
            dependencies:
              flutter:
                sdk: flutter
              cupertino_icons: ^1.0.6
            
            dev_dependencies:
              flutter_test:
                sdk: flutter
            
            flutter:
              uses-material-design: true
            EOF
          fi
          
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
