workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "stable" # или конкретная версия, например "3.19.5"
      xcode: "15.2"
    scripts:
      - name: Validate Project Structure
        script: |
          echo "Current directory: $(pwd)"
          ls -la
          if [ ! -f "pubspec.yaml" ]; then
            echo "ERROR: pubspec.yaml not found in root directory!"
            exit 1
          fi

      - name: Setup Flutter
        script: |
          flutter clean
          flutter pub cache repair
          rm -rf pubspec.lock .flutter-plugins .flutter-plugins-dependencies

      - name: Get Dependencies
        script: |
          cd "$CM_BUILD_DIR" # Важно: переход в корень проекта
          flutter pub get --verbose

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    publishing:
      email:
        recipients:
          - akhmadihin@email.com
