name: Kubiki
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
    flutter pub get
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    flutter pub get
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  flutter pub get
